#!/bin/python3

import json
import re
from sys import exit
import os.path
from os import path
if not path.exists("/zap/wrk/report.json"):
    exit("Report file not generated by zap")


fp=open("/zap/wrk/report.json","r")
json_dict=json.loads(fp.read())
fp.close()

TAG_RE=re.compile(r'<[^>]+>')

summary={}
summary["scanStart"]=json_dict["@generated"]
summary["hostName"]=json_dict["site"][0]["@name"]
summary["hostPort"]=json_dict["site"][0]["@port"]

results_array=[]
issues=0
for i in range(0,len(json_dict["site"])):
    for j in range(0,len(json_dict["site"][i]["alerts"])):
        issues=issues+1
        for k in range(0,len(json_dict["site"][i]["alerts"][j]["instances"])):
            details={}
            details["instance"]=json_dict["site"][i]["alerts"][j]["instances"][k]["uri"]
            details["name"]=json_dict["site"][i]["alerts"][j]["name"]
            details["riskLevel"]=json_dict["site"][i]["alerts"][j]["riskdesc"]
            details["description"]=TAG_RE.sub('',json_dict["site"][i]["alerts"][j]["desc"])
            details["solution"]=TAG_RE.sub('',json_dict["site"][i]["alerts"][j]["solution"])
            details["reference"]=TAG_RE.sub('',json_dict["site"][i]["alerts"][j]["reference"])
            details["cweid"]=json_dict["site"][i]["alerts"][j]["cweid"]
            results_array.append(details)

summary["issues"]=issues
results={}
if issues==0:
    details={}
    details["instance"]="No vulnerability found"
    details["name"]="No issues"
    details["riskLevel"]="NILL"
    details["description"]="No issues found"
    details["solution"]="No issues detected"
    details["reference"]="No issues found"
    details["cweid"]="0"
    results_array.append(details)
    results["summary"]=summary
    results["results"]=results_array

else:
    results["summary"]=summary
    results["results"]=results_array

fp=open("/zap/result.json","w")
fp.write(json.dumps(results))
fp.close()

print(json.dumps(results,indent=4))