version: '2'
services:
  app:
    container_name: zapper
    restart: always
    build: . #Build from git repo
    links:
      - clair
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    image: zap #Image name for Dynamic Analysis repo

  postgres:
    container_name: clair_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    image: quay.io/coreos/clair:v2.0.1
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]
